# Generated by Django 5.1.2 on 2024-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entry_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
